###1.
For an 2-dimensional input matrix, write a NumPy function to subtract the mean of each row of a given matrix.

Sample Input:

A = np.array([[1,2,5,1], [3,4,1,0]])

my_function(A)

Sample Output:

array([[-1.25, -0.25, 2.75, -1.25],
       [ 1. , 2. , -1. , -2. ]])

In [1]:
import numpy as np
def my_function(matrix):
  mymean=np.mean(matrix, axis=1, keepdims=True) # 각 행별 평균 계산
  newmatrix=matrix-mymean # 각 요소에서 평균 빼기
  return newmatrix

In [2]:
# sample input
A = np.array([[1,2,5,1],
              [3,4,1,0]])
my_function(A)

array([[-1.25, -0.25,  2.75, -1.25],
       [ 1.  ,  2.  , -1.  , -2.  ]])

### 2.
For an 2-dimensional input matrix, write a NumPy function to subtract the mean of each column of a given matrix.

Sample Input:

A = np.array([[1,2,5,1], [3,4,1,0]])

my_function(A)

Sample Output:

array([[-1. , -1. , 2. , 0.5],
 [ 1. , 1. , -2. , -0.5]])

In [3]:
import numpy as np
def my_function(matrix):
  mymean=np.mean(matrix, axis=0, keepdims=True) # 각 열별 평균 계산
  newmatrix=matrix-mymean # 각 요소에서 평균 빼기
  return newmatrix

In [4]:
# sample input
A = np.array([[1,2,5,1], [3,4,1,0]])
my_function(A)

array([[-1. , -1. ,  2. ,  0.5],
       [ 1. ,  1. , -2. , -0.5]])

### 3.
Write a NumPy function to concatenate two given two dimensional arrays of shape (n, p) and (n,q), respectively, to create (n, p+q) array.

Sample Output:

Original arrays:

[[4.5 3.5]

[5.1 2.3]]

[[1]

[2]]

Concatenated arrays:

[[4.5 3.5 1. ]

[5.1 2.3 2. ]]


In [5]:
def my_concate(a,b):
  # 가로 방향으로 concatenate하기
  result = np.concatenate((a, b), axis=1)
  return result

In [6]:
# sample input
A = np.array([[4.5, 3.5],
              [5.1, 2.3]])
B = np.array([[1],
              [2]])

my_concate(A,B)

array([[4.5, 3.5, 1. ],
       [5.1, 2.3, 2. ]])

### 4.
Write a NumPy function to concatenate two given two dimensional arrays of shape (n, p) and (m,p), respectively, to create (n+m, p) array.

Sample Output:

Original arrays:

[[4.5 3.5]

[5.1 2.3]]

[[4 3]

[5 2]

[1 1]]

Concatenate arrays:

[[4.5 3.5]

[5.1 2.3]

[4 3]

[5 2]

[1 1]]

In [7]:
def my_concate(a,b):
  # 세로 방향으로 concatenate하기
  result = np.concatenate((a, b), axis=0)
  return result

In [8]:
# sample input
A = np.array([[4.5, 3.5],
              [5.1, 2.3]])
B = np.array([[4, 3],
              [5, 2],
              [1, 1]])

my_concate(A,B)

array([[4.5, 3.5],
       [5.1, 2.3],
       [4. , 3. ],
       [5. , 2. ],
       [1. , 1. ]])

### 5
[Video Record] Create a python function to create a matrix having a boundary with a value of 1 and an inner one 0 the legend is shown below for given row and column numbers.

In [9]:
def my_matrix(i, j):

    # 모든 원소가 1인 matrix를 생성해 matrix 변수에 저장: np.ones(row, col)
    matrix = np.ones((i, j), dtype=int)
    # 테두리 부분을 제외한 부분을 0으로 대체시키기
    matrix[1:-1, 1:-1] = 0
    return matrix

In [10]:
# sample input
my_matrix(10,10)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [11]:
## Another solution)
n=10  # input

A=np.zeros([n,n])
for i in range(n):
  for j in range(n):
    if (i==0) | (i==(n-1)):
      A[i,j]=1
    if (j==0) | (j==(n-1)):
      A[i,j]=1

A

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### 6.
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below. The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Write a Python function to find moving average in an array over a window
with an array and window size as inputs:

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window size 3.

In [12]:
def moving_average(arr, k):
    n = len(arr)
    # 비어있는 list 생성하기
    moving_averages = []

    for i in range(n - k + 1):
        w = arr[i : i+k]
        # 이동평균 구하기
        avg = sum(w) / k
        # list에 moving average 추가하기
        moving_averages.append(avg)

    return moving_averages

In [13]:
# Sample function
data = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
window_size = 3

moving_average(data, window_size)

[5.0,
 4.666666666666667,
 5.666666666666667,
 6.666666666666667,
 9.666666666666666,
 28.666666666666668,
 49.333333333333336,
 72.66666666666667,
 84.0,
 93.33333333333333,
 116.33333333333333]

### 7. [Video Record]



### a)
Create an array “N” of shape [3, 5] to represent the number of accidents. Similarly, create arrays of “Salary” and “Sports” of shape [3,5] each to represent the salary and sports car.

In [14]:
# Table 1 : Number of accidents
N = np.array([[0, 1, 0, 1, 2],
               [1, 3, 2, 1, 0],
               [0, 0, 0, 1, 3]])

# Table 2 : Salary (in dollars)
Salary = np.array([[157, 167, 130, 145, 170],
               [250, 260, 263, 273, 290],
               [301, 120, 30, 100, 502]])

# Table 3 : Sports car (0: no, 1: yes)
Sports = np.array([[1, 1, 1, 1, 1],
               [0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0]])

### b)
Create an array “Y” of shape [3,5,3] where (i,j,1)-th element of “Y” represent the number of accidents of i-th id in the j-th year, and (i,j,2)-th element of “Y” represents the salary of i-th id in the j-th year, and (i,j,3)-th element of “Y” represent sports car (0 or 1) of i-th id in the j-th year. (Please type everything element to define “Y”)

In [15]:
Y = np.array([[[0,157,1],[1,167,1],[0,130,1],[1,145,1],[2,170,1]],
              [[1,250,0],[3,260,0],[2,263,0],[1,273,0],[0,290,0]],
              [[0,301,0],[0,120,0],[0,30,0],[1,100,0],[3,502,0]]])

print(Y)

[[[  0 157   1]
  [  1 167   1]
  [  0 130   1]
  [  1 145   1]
  [  2 170   1]]

 [[  1 250   0]
  [  3 260   0]
  [  2 263   0]
  [  1 273   0]
  [  0 290   0]]

 [[  0 301   0]
  [  0 120   0]
  [  0  30   0]
  [  1 100   0]
  [  3 502   0]]]


### c)
Solve part b) again by utilizing “N”, “Salary”, and “Sports” defined in a).

In [16]:
N.reshape(3,5,1)

array([[[0],
        [1],
        [0],
        [1],
        [2]],

       [[1],
        [3],
        [2],
        [1],
        [0]],

       [[0],
        [0],
        [0],
        [1],
        [3]]])

In [17]:
Salary.reshape(3,5,1)

array([[[157],
        [167],
        [130],
        [145],
        [170]],

       [[250],
        [260],
        [263],
        [273],
        [290]],

       [[301],
        [120],
        [ 30],
        [100],
        [502]]])

In [18]:
Sports.reshape(3,5,1)

array([[[1],
        [1],
        [1],
        [1],
        [1]],

       [[0],
        [0],
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        [0],
        [0]]])

In [19]:
# 차원을 늘려 합쳐야 하는 경우이므로, numpy.stack()을 사용한다.
Y_new = np.stack((N, Salary, Sports), axis = 2)
print(Y_new)

[[[  0 157   1]
  [  1 167   1]
  [  0 130   1]
  [  1 145   1]
  [  2 170   1]]

 [[  1 250   0]
  [  3 260   0]
  [  2 263   0]
  [  1 273   0]
  [  0 290   0]]

 [[  0 301   0]
  [  0 120   0]
  [  0  30   0]
  [  1 100   0]
  [  3 502   0]]]


### d)
Create an array “Y2” of shape [3,3,5] where (i,1,j)-th element of “Y” represent the number of accidents of i-th id in the j-th year, and (i,2,j)-th element of “Y” represents the salary of i-th id in the j-th year, and (i,3,j)-th element of “Y” represent sports car (0 or 1) of i-th id in the j-th year. (Please type everything element to define “Y2”)



In [20]:
Y2 = np.array([[[0,1,0,1,2],[157,167,130,145,170],[1,1,1,1,1],],
               [[1,3,2,1,0],[250,260,263,273,290],[0,0,0,0,0]],
               [[0,0,0,1,3],[301,120,30,100,502],[0,0,0,0,0]]])
print(Y2)

[[[  0   1   0   1   2]
  [157 167 130 145 170]
  [  1   1   1   1   1]]

 [[  1   3   2   1   0]
  [250 260 263 273 290]
  [  0   0   0   0   0]]

 [[  0   0   0   1   3]
  [301 120  30 100 502]
  [  0   0   0   0   0]]]


### e)
Solve part d> again by converting an array “Y” into “Y2” Hint: Use numpy.tranpose() function or numpy.swapaxes() function


In [21]:
np.transpose(Y,(0,2,1))

array([[[  0,   1,   0,   1,   2],
        [157, 167, 130, 145, 170],
        [  1,   1,   1,   1,   1]],

       [[  1,   3,   2,   1,   0],
        [250, 260, 263, 273, 290],
        [  0,   0,   0,   0,   0]],

       [[  0,   0,   0,   1,   3],
        [301, 120,  30, 100, 502],
        [  0,   0,   0,   0,   0]]])

In [22]:
Y2

array([[[  0,   1,   0,   1,   2],
        [157, 167, 130, 145, 170],
        [  1,   1,   1,   1,   1]],

       [[  1,   3,   2,   1,   0],
        [250, 260, 263, 273, 290],
        [  0,   0,   0,   0,   0]],

       [[  0,   0,   0,   1,   3],
        [301, 120,  30, 100, 502],
        [  0,   0,   0,   0,   0]]])

### f)
Solve part d> again by utilizing “N”, “Salary”, and “Sports” defined in a>

In [23]:
Y2_new = np.stack((N,Salary,Sports),axis=1)
print(Y2_new)

[[[  0   1   0   1   2]
  [157 167 130 145 170]
  [  1   1   1   1   1]]

 [[  1   3   2   1   0]
  [250 260 263 273 290]
  [  0   0   0   0   0]]

 [[  0   0   0   1   3]
  [301 120  30 100 502]
  [  0   0   0   0   0]]]
